In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('./MolMap-OOB/bace_bbbp_hiv.csv')
df1

   task_name   seed   valid_auc   test_auc
0       BACE      2    0.864777   0.885588
1       BACE     16    0.883333   0.824757
2       BACE     32    0.883790   0.856882
3       BACE     64    0.941623   0.920000
4       BACE    128    0.941517   0.786843
5       BACE    256    0.876711   0.826289
6       BACE    512    0.839217   0.942402
7       BACE   1024    0.934331   0.902156
8       BACE   2048    0.942423   0.927526
9       BACE   4096    0.852492   0.848749
10      BBBP      2    0.906710   0.939245
11      BBBP     16    0.891403   0.907028
12      BBBP     32    0.870925   0.836771
13      BBBP     64    0.902408   0.862991
14      BBBP    128    0.909117   0.931073
15      BBBP    256    0.893535   0.933284
16      BBBP    512    0.945865   0.912691
17      BBBP   1024    0.936054   0.905806
18      BBBP   2048    0.878071   0.909411
19      BBBP   4096    0.922600   0.946193
20       HIV      2    0.776482   0.754934
21       HIV     16    0.834746   0.850368
22       HIV     32    0.820499   0.828319
23       HIV     64    0.827493   0.807710
24       HIV    128    0.757286   0.807090
25       HIV    256    0.783231   0.784570
26       HIV    512    0.854705   0.731129
27       HIV   1024    0.794607   0.826013
28       HIV   2048    0.794477   0.771357
29       HIV   4096    0.826839   0.830474

In [3]:
df2 = pd.read_csv('./MolMap-OOB/sider_toxcast_tox21.csv')
df2

   task_name   seed   valid_auc   test_auc
0    ToxCast      2    0.737302   0.744973
1    ToxCast     16    0.762098   0.756415
2    ToxCast     32    0.741130   0.749137
3    ToxCast     64    0.748224   0.758894
4    ToxCast    128    0.775344   0.775721
5    ToxCast    256    0.758514   0.750644
6    ToxCast    512    0.751129   0.753628
7    ToxCast   1024    0.754299   0.745537
8    ToxCast   2048    0.758185   0.766648
9    ToxCast   4096    0.760494   0.763509
10     SIDER      2    0.675263   0.694354
11     SIDER     16    0.673341   0.638672
12     SIDER     32    0.680254   0.685639
13     SIDER     64    0.672265   0.644794
14     SIDER    128    0.679867   0.670627
15     SIDER    256    0.660047   0.673979
16     SIDER    512    0.660230   0.684626
17     SIDER   1024    0.630645   0.693188
18     SIDER   2048    0.687557   0.665723
19     SIDER   4096    0.681426   0.629024
20     Tox21      2    0.808287   0.862383
21     Tox21     16    0.831538   0.845276
22     Tox21     32    0.855573   0.844875
23     Tox21     64    0.858371   0.847778
24     Tox21    128    0.873111   0.831198
25     Tox21    256    0.832121   0.853127
26     Tox21    512    0.837696   0.831367
27     Tox21   1024    0.841695   0.858745
28     Tox21   2048    0.854578   0.845961
29     Tox21   4096    0.832601   0.833623

In [4]:
df3 = pd.read_csv('./MolMap-OOB/freesolv_esol_malaria.csv')
df3

   task_name   seed   valid_rmse   test_rmse
0   FreeSolv      2     1.274999    1.021446
1   FreeSolv     16     0.841976    1.225192
2   FreeSolv     32     1.143098    0.920290
3   FreeSolv     64     0.695804    1.102338
4   FreeSolv    128     0.813689    0.872907
5   FreeSolv    256     1.044026    1.197386
6   FreeSolv    512     0.537026    0.795627
7   FreeSolv   1024     0.914277    0.699678
8   FreeSolv   2048     1.062469    0.956128
9   FreeSolv   4096     0.747533    0.998371
10      ESOL      2     0.556226    0.625020
11      ESOL     16     0.669090    0.622491
12      ESOL     32     0.543253    0.680257
13      ESOL     64     0.557231    0.642098
14      ESOL    128     0.668502    0.670821
15      ESOL    256     0.553313    0.631959
16      ESOL    512     0.672338    0.530947
17      ESOL   1024     0.614062    0.506991
18      ESOL   2048     0.465430    0.605428
19      ESOL   4096     0.600432    0.578817
20   Malaria      2     1.039580    0.967276
21   Malaria     16     1.037238    0.981547
22   Malaria     32     0.951960    1.047087
23   Malaria     64     0.996574    0.994967
24   Malaria    128     0.997945    0.996860
25   Malaria    256     0.987913    1.051546
26   Malaria    512     1.073566    1.086012
27   Malaria   1024     1.049624    0.967052
28   Malaria   2048     1.037060    0.991413
29   Malaria   4096     0.979539    0.981325

In [5]:
model_name = 'MMNB-OOTB'

In [6]:
df1['test_metric'] = 'ROC_AUC'
df1['test_performance'] = df1[' test_auc']
df1['model'] = model_name
df1['split'] = 'scaffold'
df1['seed'] = df1[' seed']
df1 = df1[["task_name","seed", "split", "test_metric","test_performance","model"]]

In [7]:
df2['test_metric'] = 'ROC_AUC'
df2['test_performance'] = df2[' test_auc']
df2['model'] = model_name
df2['split'] = 'random'
df2['seed'] = df2[' seed']
df2 = df2[["task_name","seed", "split", "test_metric","test_performance","model"]]

In [8]:
df3['test_metric'] = 'RMSE'
df3['test_performance'] = df3[' test_rmse']
df3['model'] = model_name
df3['split'] = 'random'
df3['seed'] = df3[' seed']
df3 = df3[["task_name","seed", "split", "test_metric","test_performance","model"]]

In [9]:
df1.append(df2).append(df3).round(3).to_csv('./results_molmap.csv')